config/routes.rb
Rails.application.routes.draw do
  root 'bookstore_pages#home'

  put '/checkout', to: 'bookstore_pages#buy'

  get '/buyers/signup', to: 'buyers#new'
  get '/sellers/signup', to: 'sellers#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :buyers do
    resources :orders
  end
  resources :sellers
  resources :books
end

app/models/app_earning.rb
class AppEarning < ApplicationRecord
  validates_inclusion_of :singleton_guard, in: [0]

  def self.instance
    first_or_create!(singleton_guard: 0)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one :order, dependent: :destroy
  has_one :buyer, through: :order
  belongs_to :seller

  validates :title, :description, :author, :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 0 }

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      # returns books that don't have an order
      left_outer_joins(:order).where(orders: { book_id: nil })
    end
  end
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  after_create :update_balance

  has_many :orders, dependent: :destroy
  has_many :books, through: :orders

  validates :name, :email, :address, presence: true
  validates :balance, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  validate :unique_email

  def unique_email
    errors.add(:email, 'is already taken') if Seller.where(email: email).exists?
  end

  def update_balance
    signup_bonus = 50
    update(balance: signup_bonus)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer
  belongs_to :book

  after_create_commit do
    OrderBroadcastJob.perform_later(book_id)
  end

  before_destroy do
    DeleteOrderBroadcastJob.perform_later(self)
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_many :registered_books, foreign_key: 'seller_id', class_name: 'Book', dependent: :destroy

  validates :name, :email, :phone, presence: true
  validates :earnings, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  validate :unique_email

  def unique_email
    errors.add(:email, 'is already taken') if Buyer.where(email: email).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def check_for_buyers
    redirect_to root_path if current_user.is_a?(Seller)
  end

  def check_for_sellers
    redirect_to root_path if current_user.is_a?(Buyer)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in?
  before_action :check_for_buyers, only: %i[index update]
  before_action :check_for_sellers, only: %i[new create]

  def index
    @bought_books = current_user.books.where(sold: true)
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.registered_books.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def logged_in?
    redirect_to login_path if current_user.nil?
  end

  def book_params
    params.require(:book).permit(:title, :description, :author, :price)
  end
end

app/controllers/bookstore_pages_controller.rb
class BookstorePagesController < ApplicationController
  before_action :logged_in?

  def home
    @books = Book.search(params[:search])

    return unless current_user.is_a?(Seller)

    @registered_books = Book.where(seller_id: current_user.id)
    @sold_books = @registered_books.where(sold: true)
  end

  def buy
    @books = current_user.books.where(sold: false)
    @balance = current_user.balance
    @app_earnings = AppEarning.instance

    @books&.each do |book|
      book.update(sold: true)

      @balance -= book.price
      break if @balance.negative?

      book.buyer.decrement!(:balance, book.price)
      book.seller.increment!(:earnings, book.price - 1)
      @app_earnings.increment!(:earnings, 1)
    end
    redirect_to books_path
  end

  private

  def logged_in?
    redirect_to login_path if current_user.nil?
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :logged_in?, only: [:show]
  before_action :check_for_buyers, only: [:show]

  def show
    @buyer = Buyer.find(current_user.id)
  end

  def new
    @buyer = Buyer.new
  end

  def create
    @buyer = Buyer.new(buyer_params)

    if @buyer.save
      log_in @buyer
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def logged_in?
    redirect_to login_path if current_user.nil?
  end

  def buyer_params
    params.require(:buyer).permit(:name, :email, :address, :password, :password_confirmation)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_for_buyers
  before_action :logged_in?

  def index
    @cart_books = current_user.books.where(sold: false)
  end

  def create
    @book = Book.find(params[:book_id])
    current_user.books << @book if @book
  end

  def destroy
    @book = Book.find(params[:book_id])
    return if @book.sold

    @order = Order.find_by(book_id: params[:book_id])
    @order&.destroy
  end

  private

  def logged_in?
    redirect_to login_path if current_user.nil?
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :logged_in?, only: [:show]
  before_action :check_for_sellers, only: [:show]

  def show
    @seller = Seller.find(current_user.id)
  end

  def new
    @seller = Seller.new
  end

  def create
    @seller = Seller.new(seller_params)

    if @seller.save
      log_in @seller
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def logged_in?
    redirect_to login_path if current_user.nil?
  end

  def seller_params
    params.require(:seller).permit(:name, :phone, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = Buyer.find_by(email: params[:session][:email].downcase) ||
            Seller.find_by(email: params[:session][:email].downcase)

    if @user&.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out unless current_user.nil?
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/bookstore_pages_helper.rb
module BookstorePagesHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:email] = user.email
  end

  def current_user
    return unless session[:email]

    user_email = session[:email]
    @current_user ||= Buyer.find_by(email: user_email) ||
                      Seller.find_by(email: user_email)
  end

  def log_out
    session.delete(:email)
    @current_user = nil
  end
end

app/views/books/index.html.erb
<div class="row">
  <% for book in @bought_books %>
    <div class="col-sm-6 col-lg-4">
      <div class="card my-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= book.title %></h5>
          <blockquote class="blockquote mb-0">
            <p><%= book.description %></p>
            <footer class="blockquote-footer text-right"><cite title="Source Title"><%= book.author %></cite></footer>
          </blockquote>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="container" style="max-width: 500px">
  <h4 class="text-center mt-5">Add a new book for sale!</h4>
  <%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
      <div>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control'%>
    </div>
    <div class="text-center">
      <%= f.submit 'Add Book', class: 'btn btn-primary mt-2 mb-5' %>
    </div>
  <% end %>
</div>

app/views/bookstore_pages/home.html.erb
<% if current_user.is_a?(Buyer)%>

  <h2 class="mt-5 text-center">Welcome to Book Store!</h2>
  
  <div class="container">
    <div class="row">
      <div class="col-md-12 px-0">
        <%= form_tag root_path, method: :get, class: 'mt-5' do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], class: 'form-control' %>
            <span class="input-group-btn">
              <button type="submit", class="btn btn-secondary mb-2 ml-2">Search</button>
            </span> 
          </div> 
        <% end %>
      </div>
    </div>
  </div>

  <div class="row mt-5" id="books">
    <% @books.each do |book|%>
      <% if !book.sold %>
        <div class="col-sm-6 col-lg-4" id="book-<%=book.id %>">
          <div class="card my-3" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= book.title.capitalize() %></h5>
              <blockquote class="blockquote mb-0">
                <p class="h6"><%= book.description %></p>
                <footer class="blockquote-footer text-right"><cite title="Source Title"><%= book.author %></cite></footer>
              </blockquote>
              <div class="text-center mt-4">
                <%= form_tag buyer_orders_path(current_user.id), method: :post, remote: true do %>
                  <p class="mb-0">
                    <%= hidden_field_tag :book_id, book.id %>
                    <button type="submit" class="btn btn-outline-success">Add to Cart</button>
                  </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

<% else %>
  <h4 class="mt-5 mb-3 text-center">Registered Books</h4>
  <div class="row">
    <% for book in @registered_books %>
      <div class="col-sm-6 col-lg-4">
        <div class="card my-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= book.title %></h5>
            <blockquote class="blockquote mb-0">
              <p><%= book.description %></p>
              <footer class="blockquote-footer text-right"><cite title="Source Title"><%= book.author %></cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <h4 class="mt-5 mb-3 text-center">Sold Books</h4>
  <div class="row">
    <% for book in @sold_books %>
      <div class="col-sm-6 col-lg-4">
        <div class="card my-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= book.title %></h5>
            <blockquote class="blockquote mb-0">
              <p><%= book.description %></p>
              <footer class="blockquote-footer text-right"><cite title="Source Title"><%= book.author %></cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/buyers/new.html.erb
<div class="container" style="max-width: 500px">
  <h4 class="text-center mt-5">Start buying, sign up!</h4>
  <%= form_for(@buyer) do |f| %>
    <% if @buyer.errors.any? %>
      <div>
        <ul>
          <% @buyer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label 'email:' %>
      <%= f.email_field :email, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label 'address:' %>
      <%= f.text_field :address, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label 'password:' %>
      <%= f.password_field :password, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label 'password_confirmation:' %>
      <%= f.password_field :password_confirmation, class: 'form-control'%>
    </div>
    <div class="text-center">
      <%= f.submit 'Sign up', class: 'btn btn-secondary mt-2 mb-5' %>
    </div>
  <% end %>
  <p class="mb-1">Want to sell? <%= link_to "Sign up now!", new_seller_path %></p>
  <small>Already have an account? <%= link_to "Log in", login_path %></small>
</div>

app/views/buyers/show.html.erb
<div class="container" style="width: 500px">
  <h4 class="text-center my-5">My Information</h4>
  <div>
    <p class="my-4">Name: <span><%= @buyer.name %></span></p>
    <p class="my-4">Address: <span><%= @buyer.address %></span></p>
    <p class="my-4">Email: <span><%= @buyer.email %></span></p>
    <p class="my-4">Balance: <span class="text-success">$<%= @buyer.balance %></span></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-light justify-content-between">
  <div class="container">
    <%= link_to 'Book Store', root_path, class: 'navbar-brand' %>
    <div class="d-flex justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <% if current_user %>
          <% if current_user.is_a?(Seller)%>
            <li class="nav-item">
              <%= link_to 'New Book', new_book_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'My Books', books_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Cart', buyer_orders_path(current_user.id), class: 'nav-link' %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", current_user.is_a?(Seller)? seller_path(current_user) : buyer_path(current_user), class: 'dropdown-item' %>
                <%= link_to "Log out", logout_path, method: :delete, class: 'dropdown-item' %> 
              </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_book.html.erb
<div class="col-sm-6 col-lg-4" id="book-<%=book.id %>">
  <div class="card my-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= book.title.capitalize() %></h5>
      <blockquote class="blockquote mb-0">
        <p class="h6"><%= book.description %></p>
        <footer class="blockquote-footer text-right"><cite title="Source Title"><%= book.author %></cite></footer>
      </blockquote>
      <div class="text-center mt-4">
        <%= form_tag buyer_orders_path(current_user.id), method: :post, remote: true do %>
          <p class="mb-0">
            <%= hidden_field_tag :book_id, book.id %>
            <button type="submit" class="btn btn-outline-success">Add to Cart</button>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/destroy.js.erb
Rails.$("#book-<%= @book.id %>")[0].remove()

app/views/orders/index.html.erb
 <div class="row">
  <% for book in @cart_books %>
    <div class="col-sm-6 col-lg-4" id="book-<%=book.id %>">
      <div class="card my-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= book.title.capitalize() %></h5>
          <blockquote class="blockquote mb-0">
            <footer class="blockquote-footer text-right"><cite title="Source Title"><%= book.author %></cite></footer>
          </blockquote>
          <div class="text-center mt-4">
            <%= form_tag buyer_order_path(current_user.id, book.order.id), method: :delete, remote: true do %>
              <p class="mb-0">
                <%= hidden_field_tag :book_id, book.id %>
                 <button type="submit" class="btn btn-outline-danger">Remove from Cart</button>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% if @cart_books.count.positive? %>
  <%= form_tag '/checkout', method: :put, class: 'text-center mt-5' do %>
    <p>
      <%= submit_tag "Buy", class: 'btn btn-success' %>
    </p>
  <% end %>
<% end %>

app/views/sellers/new.html.erb
<div class="container" style="max-width: 500px">
  <h4 class="text-center mt-5">Start selling, sign up!</h4>
  <%= form_for(@seller) do |f| %>
    <% if @seller.errors.any? %>
      <div>
        <ul>
          <% @seller.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label 'email:' %>
      <%= f.email_field :email, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label 'phone:' %>
      <%= f.text_field :phone, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label 'password:' %>
      <%= f.password_field :password, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label 'password_confirmation:' %>
      <%= f.password_field :password_confirmation, class: 'form-control'%>
    </div>
    <div class="text-center">
      <%= f.submit 'Sign up', class: 'btn btn-secondary mt-2 mb-5' %>
    </div>
  <% end %>
  <p class="mb-1">Want to buy? <%= link_to "Sign up now!", new_buyer_path %></p>
  <small>Already have an account? <%= link_to "Log in", login_path %></small>
  
</div>

app/views/sellers/show.html.erb
<div class="container" style="width: 500px">
  <h4 class="text-center my-5">My Information</h4>
  <div>
    <p class="my-4">Name: <span><%= @seller.name %></span></p>
    <p class="my-4">Address: <span><%= @seller.phone %></span></p>
    <p class="my-4">Email: <span><%= @seller.email %></span></p>
    <p class="my-4">Earnings: <span class="text-success">$<%= @seller.earnings %></span></p>
  </div>
</div>